  global:
    scrape_interval: 5s
    evaluation_interval: 15s
    external_labels:
      monitor: "my-project"

  rule_files:
    - "alert.rules.yml"

  alerting:
    alertmanagers:
      - scheme: http
        static_configs:
          - targets:
              - "alertmanager:9093"

  scrape_configs:
    - job_name: "prometheus"
      scrape_interval: 5s
      static_configs:
        - targets: ["localhost:9090"]

    - job_name: "my-api"
      scrape_interval: 5s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: ["web-api1:5000", "web-api2:5000", "192.168.1.114:5005"]

    - job_name: "node-exporter"
      scrape_interval: 5s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: ["node-exporter:9100"]